name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 3.2.3
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.3
        bundler-cache: true
    - name: Build and test with Rake
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec rake
